name: Release (Build on Tag)

on:
  push:
    tags: "*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: ndk
      uses: nttld/setup-ndk@v1.0.6
      with: 
        ndk-version: r21e
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: OpenSSL keystore
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Test with Gradle
      run: ./gradlew test
    - name: assembleRelease
      run: ./gradlew assembleRelease
    - name: debug
      run: find . -name *.apk
    - name: Sign app APK
      uses: Tlaster/android-sign@v1.2.2
      with:
        releaseDirectory: project/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        output: build/release/signed
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: "34.0.0"
    - name: play store
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        packageName: de.earthlingz.oerszebra
        releaseFiles: build/release/signed/*.apk
        track: beta
        inAppUpdatePriority: 2
        userFraction: 0.33
        status: inProgress
        whatsNewDirectory: whatsnew
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/release/signed/*.apk
        file_glob: true
        tag: ${{ github.ref }}
        overwrite: true
        body: "This is my release text"
